import type { Metadata } from "next";
import { Syne, DM_Sans, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";

const syne = Syne({
  subsets: ["latin"],
  variable: "--font-syne",
});
const dmSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-dm-sans",
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${dmSans.variable} ${syne.variable} ${geistMono.variable} antialiased bg-[var(--color-background)] relative overflow-x-hidden`}>
        {/* Light mode SVG blobs */}
        <svg
          className="pointer-events-none fixed top-[-120px] left-[-120px] w-[480px] h-[480px] z-0 opacity-20 dark:hidden"
          viewBox="0 0 400 400"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
        >
          <ellipse cx="200" cy="200" rx="200" ry="140" fill="#b2f7ef" />
        </svg>
        <svg
          className="pointer-events-none fixed bottom-[-120px] right-[-120px] w-[480px] h-[480px] z-0 opacity-15 dark:hidden"
          viewBox="0 0 400 400"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
        >
          <ellipse cx="200" cy="200" rx="200" ry="140" fill="#ffe29a" />
        </svg>
        {/* Dark mode SVG blobs */}
        <svg
          className="pointer-events-none fixed top-[-120px] left-[-120px] w-[480px] h-[480px] z-0 opacity-20 hidden dark:block"
          viewBox="0 0 400 400"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
        >
          <ellipse cx="200" cy="200" rx="200" ry="140" fill="var(--color-primary)" />
        </svg>
        <svg
          className="pointer-events-none fixed bottom-[-120px] right-[-120px] w-[480px] h-[480px] z-0 opacity-15 hidden dark:block"
          viewBox="0 0 400 400"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
        >
          <ellipse cx="200" cy="200" rx="200" ry="140" fill="var(--color-accent)" />
        </svg>
        <ThemeProvider attribute="data-theme" defaultTheme="dark" enableSystem={false}>
        {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
